---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(tidytuesdayR)
library(scales)
```


```{r}
tuesdata <- tidytuesdayR::tt_load('2020-09-22')
```


```{r}
peaks <- tuesdata$peaks
members <- tuesdata$members
expeditions <- tuesdata$expeditions
```

We'll define a couple more variables we can use in the logit models.

```{r}
expeditions$staff_share = expeditions$hired_staff/(expeditions$members + expeditions$hired_staff)
expeditions$staff_share_laplace = (expeditions$hired_staff + 1)/(expeditions$members + expeditions$hired_staff + 2)

mixed_gender <- logical(nrow(expeditions))
for (i in 1:nrow(expeditions)) {
  mixed_gender[[i]] <- members[members$expedition_id == expeditions$expedition_id[[i]], ] %>%
    filter(hired == "FALSE") %>%
    .$sex %>%
    .[!is.na(.)] %>%
    unique() %>%
    length() %>%
    if (. == 2) TRUE else if (. != 1) NA
}; rm(i)

mixed_citizenship <- logical(nrow(expeditions))
for (i in 1:nrow(expeditions)) {
  mixed_citizenship[[i]] <- members[members$expedition_id == expeditions$expedition_id[[i]], ] %>%
    filter(hired == "FALSE") %>%
    .$citizenship %>%
    .[!is.na(.)] %>%
    unique() %>%
    length() %>%
    if (. >=2 ) TRUE
}; rm(i)

expeditions$mixed_gender <- mixed_gender
expeditions$mixed_citizenship <- mixed_citizenship

# We need to rearrange expeditions to add n_previous_ascends.
expeditions <- expeditions %>%
  arrange(year, peak_id)

expeditions$n_previous_ascends <- rep(0, times = nrow(expeditions))

for (i in 1:nrow(expeditions)) {
  if (expeditions$termination_reason[[i]] == "Success (main peak)") {
    peak_id = expeditions$peak_id[[i]]
    for (j in i:nrow(expeditions)) {
      if (expeditions$peak_id[[j]] == peak_id) {
        expeditions$n_previous_ascends[[j]] = expeditions$n_previous_ascends[[j]] + 1
      }
    }
    if (i %% 100 == 0) print(paste(round(i/100), "%"))
  }
}; rm(i, j)

expeditions <- expeditions %>% left_join(select(peaks, height_metres, peak_id), 
                          by = "peak_id", copy = TRUE)

expeditions$base2high <- expeditions$highpoint_date - expeditions$basecamp_date

# Check if columns have been defined correctly.
(colnames(expeditions)[17:23] == c("staff_share", "staff_share_laplace", "mixed_gender",
                                  "mixed_citizenship", "n_previous_ascends", "base2high",
                                  "height_metres")) %>% all()

expeditions
```

```{r}
saveRDS(expeditions, file = "expeditions.rds")
saveRDS(members, file = "members.rds")
saveRDS(peaks, file = "peaks.rds")
```

```{r}
library(tidyverse)
library(tidytuesdayR)
library(scales)

expeditions = readRDS(file = "expeditions.rds")
members = readRDS(file = "members.rds")
peaks = readRDS(file = "peaks.rds")
```


Data exploration based on the Tidy Tuesday screencast (https://youtu.be/WT7FMn-_jPY)

```{r}
peaks %>%
  arrange(desc(height_metres)) %>%
  head(15) %>%
  mutate(peak_name = fct_reorder(peak_name, height_metres)) %>%
  ggplot(aes(height_metres, peak_name, fill = climbing_status)) +
  geom_col() +
  labs(x = "Height (meters)",
       y = "",
       title = "Tallest Himalayan Peaks")

expeditions %>%
  group_by(peak_name) %>%
  summarize(n_climbs = n(),
            across(members:hired_staff_deaths, sum),
            first_climb = min(year)) %>%
  arrange(desc(n_climbs)) %>%
  head(11) %>%
  ggplot(aes(peak_name, n_climbs)) +
  geom_col()

members %>%
  group_by(peak_id) %>%
  summarize(n_climbs = n()) %>%
  arrange(desc(n_climbs))
```

Some information about Kangchenjunga

```{r}
expeditions[expeditions$peak_name == "Kangchenjunga", ]

expeditions %>%
  filter(peak_name == "Kangchenjunga") %>%
  mutate(termination_reason = factor(termination_reason)) %>%
  group_by(termination_reason) %>%
  tally() %>%
  arrange(desc(n))

expeditions %>%
  filter(peak_name == "Kangchenjunga") %>%
  filter(year >= 1990)

members[members$expedition_id == "KANG91102", ]

```

Make a tibble with our variables for a list of peaks.

```{r}

build_df <- function(peak_ids) {
  fi <- TRUE # First iteration
  for (id in peak_ids) {
    peak <- members %>%
      left_join(expeditions, by = c("expedition_id"), 
                suffix = c(".m", ".e")) %>%
      add_column(., leader_or_climber = (grepl("Leader", .$expedition_role, TRUE) |
                                         grepl("Climber", .$expedition_role, TRUE))) %>%
      filter(peak_id.m == id,
             year.m >= 1990) %>%
      select(peak_id.m, died, success, expedition_id, member_id, year.m, season.m, sex, age, expedition_role,
             hired, leader_or_climber, solo, oxygen_used.m, staff_share_laplace, mixed_gender, mixed_citizenship,
             n_previous_ascends, base2high, height_metres)
    
    if (fi) df <- peak else df <- df %>% add_row(peak)
    if (fi) fi <- FALSE
  }; rm(fi)
  return(df)
} 

```


```{r}

df <- build_df(c("EVER", "CHOY", "AMAD", "MANA", "DHA1", "MAKA", "LHOT", "BARU", "PUMO", "ANN1", "KANG", "HIML"))
saveRDS(df, "df.rds")

```

```{r}
peak <- members %>%
  left_join(expeditions, by = c("peak_id"), 
            suffix = c(".m", ".e")) %>%
  add_column(., leader_or_climber = (grepl("Leader", .$expedition_role, TRUE) |
                                     grepl("Climber", .$expedition_role, TRUE))) %>%
  filter(peak_id == "KANG",
         year >= 1990,
         hired == "FALSE") %>%
  select(peak_id, died, success, expedition_id, member_id, year, season, sex, age, expedition_role,
         leader_or_climber, solo, oxygen_used.m, staff_share_laplace, mixed_gender,
         mixed_citizenship, n_previous_ascends, base2high, height_metres)


left_join(members, expeditions, by = "peak_id") 
expeditions['peak_id']



str(members)
str(expeditions)
```


No clue what's below! Haha
---------------------------------------------------------------------------------------

```{r}
expeditions %>%
  group_by(year) %>%
  filter(year > 1945) %>%
  summarise(fatality_rate = round(sum(member_deaths)/sum(members), 2)) %>%
  ggplot(aes(x = year, y = fatality_rate)) +
  geom_point() +
  geom_smooth()
```

```{r}
expeditions %>%
  group_by(year) %>%
  filter(year > 1945) %>%
  summarise(fatality_rate = round(sum(hired_staff_deaths)/sum(hired_staff), 2)) %>%
  ggplot(aes(x = year, y = fatality_rate)) +
  geom_point() +
  geom_smooth()
```

```{r}
members %>%
  group_by(injury_type) %>%
  summarise(mean(injury_height_metres, na.rm = TRUE))
```
```{r}
mountain <- factor(members$peak_id)
oxygen <- factor(members$oxygen_used)
x <- glm(data = members, died ~ oxygen + mountain, family = "binomial")

summary(x)
members$injury_type.
```


```{r}
x <- expeditions %>%
  group_by(peak_name) %>%
  tally()

x[[2]][order(x$n, decreasing = TRUE)]
x[[1]][order(x$n, decreasing = TRUE)]
```
```{r}
str(expeditions)
```

```{r}
library(dplyr)
example("left_join")

"tidyverse"
```

